# Generated by Django 5.2.3 on 2026-04-19 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_promocode_payment_promo_code'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('location_description', models.CharField(blank=True, max_length=200)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='conference.conference')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('conference', 'name')},
            },
        ),
        migrations.AddField(
            model_name='session',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='schedule.room'),
        ),
    ]
