# Generated by Django 5.2.3 on 2026-05-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_promocode_payment_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
